### ISSUE TITLE
Users not importing

### ISSUE THREAD

**Issue by MTThorsen** [Alec-Bailey/IncidentIQ-Data-Sync#2]
After setting up the config.ini file and running main.py Assets, AssetCustomFields, and Locations are populated correctly. However, while the code is going through users I am getting the error `A non pyodbc error occured - refer to documenation (builtins.ValueError) bytes is not a 16-char string` followed by the SQL insert statements 8 times. Each set of statements is rather large with the error message saying it is truncating several hundred thousand characters.

**Comment by Alec-Bailey** [comment]
Hi @MTThorsen - apologies for the delayed response. Would you mind sharing which exact DBMS you are using?

**Comment by MTThorsen** [comment]
I am using MySQL. I was able to get it to pull the users by excluding the ExternalId from the users in the user.py file

**Comment by Alec-Bailey** [comment]
Do you notice in the response from your IIQ instance that ExternalId is not present?

**Comment by jcolinger3** [comment]
Hi Alec. I work with Michael. Thanks for this project. It got us by for a while, and we still use it. But iiQ has added a feature that allows Views to be sftp'd. This combined with Airbyte should allow us to get anything we need from iiQ.  We haven't tested it yet, just finishing some set up. But thought I'd let you know we appreciate your project as it was very helpful to us.

**Comment by Alec-Bailey** [comment]
So glad you were able to get some use out if it; I was happy to be able to open source it.

Given that information I will likely archive this project, as I no longer have access to an IIQ instance and it seems it is not needed.

All the best!
